### ISSUE TITLE
2x slankmatis dirbtuvėse

### ISSUE THREAD

**Issue by ghost** [makerspacelt/hq#3]
Ar reikia pirkti mums dirbtuvėse antrą slankmatį? Ar gal kas turi užsilikusį?

**Comment by dariuskt** [comment]
Galvot, manau, reiktų apie paprastą, pigų, nes čia žmonėms jis kurkas dažniau iškrenta iš rankų, tai ivestuoti tikrai neverta.

**Comment by ghost** [comment]
Na, pas mus apskritai nėra brangių įrankių, tai ir nemaniau apie brangaus pirkimą. Svarbu, kad matuotų.

**Comment by dariuskt** [comment]
+1
na taip, čia aš labiau apie tai, kad jeigu kas turi atliekamą tai geriau nelabai brangų ;)

**Comment by grinkus** [comment]
:+1:

**Comment by dariuskt** [comment]
Nupirkau turguje, 6eur, apgyvendinau prei grąžtų stalčiuje.
