### ISSUE TITLE
MIG (kempas, pusautomatis) įsigijimas

### ISSUE THREAD

**Issue by dariuskt** [makerspacelt/hq#5]
Vaidas siulo 300e MIGo isigijimui, pasidairius sian bei ten atrodo jog pigiausias vertas bent kazkiek demesio [variantas](http://www.prekybairankiais.lt/Suvirinimo-aparatai/Suvirinimo-pusautomaciai-MIG-MAG/Suvirinimo-pusautomatis-MIG-200-AI.html) kainuoja brangiau. Be to reikes papildomai isigyti CO2 baliona, duju srauto reguliatoriu ir kazkokiu slangu viskam sujungti. Tiksliai nezinau kiek tai sudaro papildomu islaidu, bet klausimas yra **ar naudojam makerspace biudzeta** sitam skirtumui padengti, kad tureti pilna komplekta?

**Comment by ghost** [comment]
ne į temą, bet "įsigijimas", o ne "isigyjimas"

**Comment by dariuskt** [comment]
Kadangi daugiau nei savaitę nieks neprieštaravo bei nepasiūlė geresnių variantų tai šiandien ir bandysim iš makerspace biudžeto nupirkti užpildytą balioną.

**Comment by grinkus** [comment]
Labai gerai. Aš vis neprisiruošiau parašyti, kad, mano galva, visai nemažai žmonių pravers jis ir bus daiktas galintis praversti žmonėms, kurie dar makerspace nelanko :) tai lyg ir logiška būtų naudoti bendrą biudžetą tam

**Comment by dariuskt** [comment]
Viskas nupirkta ir jau paruošta naudoti purvinose dirbtuvėse ;)

**Comment by grinkus** [comment]
Congrats :)
